"""empty message

Revision ID: 711737e80427
Revises: fd06c6b65112
Create Date: 2020-02-16 21:51:57.197936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711737e80427'
down_revision = 'fd06c6b65112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Recipe', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recipe', type_='foreignkey')
    op.drop_column('Recipe', 'user_id')
    # ### end Alembic commands ###
