"""empty message

Revision ID: fb37e5dc89a7
Revises: f39cb6b58904
Create Date: 2020-02-16 21:22:23.844969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb37e5dc89a7'
down_revision = 'f39cb6b58904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Language')
    op.add_column('Category', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Category', 'slug')
    op.create_table('Language',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Language_id_seq"\'::regclass)'), nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Language_pkey')
    )
    # ### end Alembic commands ###
