"""empty message

Revision ID: fd06c6b65112
Revises: 290eeb9858c1
Create Date: 2020-02-16 21:29:22.160442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd06c6b65112'
down_revision = '290eeb9858c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('User', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('User', 'id')
    # ### end Alembic commands ###
